function G = G4(in1,in2)
%G4
%    G = G4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Jun-2019 23:05:56

K1 = in1(:,13);
K2 = in1(:,14);
K3 = in1(:,15);
K4 = in1(:,16);
qR1 = in2(:,1);
qR2 = in2(:,2);
qR3 = in2(:,3);
qR4 = in2(:,4);
G = [K1.*qR1;K2.*qR2;K3.*qR3;K4.*qR4];
