function G = G5(in1,in2)
%G5
%    G = G5(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Jun-2019 23:28:08

K1 = in1(:,16);
K2 = in1(:,17);
K3 = in1(:,18);
K4 = in1(:,19);
K5 = in1(:,20);
qR1 = in2(:,1);
qR2 = in2(:,2);
qR3 = in2(:,3);
qR4 = in2(:,4);
qR5 = in2(:,5);
G = [K1.*qR1;K2.*qR2;K3.*qR3;K4.*qR4;K5.*qR5];
