function Jac = J4(in1,in2)
%J4
%    JAC = J4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Jun-2019 23:05:56

L1 = in1(:,5);
L2 = in1(:,6);
L3 = in1(:,7);
L4 = in1(:,8);
qR1 = in2(:,1);
qR2 = in2(:,2);
qR3 = in2(:,3);
qR4 = in2(:,4);
t2 = qR1+qR2;
t3 = cos(t2);
t4 = qR3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = qR4+t4;
t8 = sin(t4);
t9 = L2.*t3;
t10 = L2.*t5;
t11 = cos(t7);
t12 = sin(t7);
t13 = L3.*t6;
t14 = L3.*t8;
t17 = -t10;
t15 = L4.*t11;
t16 = L4.*t12;
t18 = -t14;
t19 = -t16;
Jac = reshape([t17+t18+t19-L1.*sin(qR1),t9+t13+t15+L1.*cos(qR1),t17+t18+t19,t9+t13+t15,t18+t19,t13+t15,t19,t15],[2,4]);
