function Jac = J5(in1,in2)
%J5
%    JAC = J5(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Jun-2019 23:28:08

L1 = in1(:,6);
L2 = in1(:,7);
L3 = in1(:,8);
L4 = in1(:,9);
L5 = in1(:,10);
qR1 = in2(:,1);
qR2 = in2(:,2);
qR3 = in2(:,3);
qR4 = in2(:,4);
qR5 = in2(:,5);
t2 = qR1+qR2;
t3 = cos(t2);
t4 = qR3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = qR4+t4;
t8 = sin(t4);
t9 = L2.*t3;
t10 = L2.*t5;
t11 = cos(t7);
t12 = qR5+t7;
t13 = sin(t7);
t15 = L3.*t6;
t16 = L3.*t8;
t20 = -t10;
t14 = sin(t12);
t17 = cos(t12);
t18 = L4.*t11;
t19 = L4.*t13;
t23 = -t16;
t21 = L5.*t17;
t22 = L5.*t14;
t24 = -t19;
t25 = -t22;
Jac = reshape([t20+t23+t24+t25-L1.*sin(qR1),t9+t15+t18+t21+L1.*cos(qR1),t20+t23+t24+t25,t9+t15+t18+t21,t23+t24+t25,t15+t18+t21,t24+t25,t18+t21,t25,t21],[2,5]);
