function pFR = visualize5(in1,in2)
%VISUALIZE5
%    PFR = VISUALIZE5(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Jun-2019 23:28:08

L1 = in2(:,1);
L2 = in2(:,2);
L3 = in2(:,3);
L4 = in2(:,4);
L5 = in2(:,5);
LCenter = in2(:,6);
qR1 = in1(:,1);
qR2 = in1(:,2);
qR3 = in1(:,3);
qR4 = in1(:,4);
qR5 = in1(:,5);
t2 = cos(qR1);
t3 = sin(qR1);
t4 = qR1+qR2;
t5 = L1.*t2;
t6 = L1.*t3;
t7 = cos(t4);
t8 = qR3+t4;
t9 = sin(t4);
t10 = cos(t8);
t11 = qR4+t8;
t12 = sin(t8);
t13 = L2.*t7;
t14 = L2.*t9;
t15 = cos(t11);
t16 = qR5+t11;
t17 = sin(t11);
t18 = L3.*t10;
t19 = L3.*t12;
t20 = L4.*t15;
t21 = L4.*t17;
pFR = reshape([LCenter,0.0,LCenter+t5,t6,LCenter+t5+t13,t6+t14,LCenter+t5+t13+t18,t6+t14+t19,LCenter+t5+t13+t18+t20,t6+t14+t19+t21,LCenter+t5+t13+t18+t20+L5.*cos(t16),t6+t14+t19+t21+L5.*sin(t16)],[2,6]);
